### ISSUE TITLE
[ISSUE] Can't open PC sheet on SWADE

### ISSUE THREAD

**Issue by ChrisCB65** [ironmonk88/monks-enhanced-journal#212]
When Monk's enhanced journal is active with the SWADE system, you can not open PC sheets.

- Foundry : 9 build 249
- System : SWADE 1.0.4
- Monk's Enhanced Journal : v1.0.46

This is probably not a problem due to an interaction with another module. I have disabled all of them except Monk's Enhanced Journal and the issue is still there.

Here is the console output when I try to open a PC's sheet.

    foundry.js:316 
        
       TypeError: An error occurred while rendering CharacterSheet 42: Cannot read properties of undefined (reading 'testUserPermission')
    at TextEditor._createContentLink (monks-enhanced-journal.js:575:30)
    at Function._replaceTextContent (foundry.js:44616:29)
    at Function.enrichHTML (foundry.js:44497:30)
    at Function.TextEditor.constructor.enrichHTML (monks-enhanced-journal.js:235:38)
    at SwadeItem.<anonymous> (handlebarsHelpers.js:39:53)
    at SwadeItem.c (handlebars.min.js:27:19853)
    at eval (eval at createFunctionContext (handlebars.min.js:29:1808), <anonymous>:11:145)
    at Object.h [as fn] (handlebars.min.js:27:17870)
    at SwadeItem.<anonymous> (handlebars.min.js:27:10117)
    at SwadeItem.c (handlebars.min.js:27:19853)
    onError @ foundry.js:316
    (anonymes) @ foundry.js:3023
    Promise.catch (asynchrone)
    render @ foundry.js:3021
    render @ foundry.js:4259
    _onClickDocumentName @ foundry.js:47362
    dispatch @ jquery.min.js:2
    v.handle @ jquery.min.js:2

**Comment by Deadlander** [comment]
I have had this same exact error. As soon as the Enhanced Journal is turned off, everything works fine.

**Comment by ironmonk88** [comment]
Should be fixed now.
It looks like you had a broken link that was causing issues.

**Comment by ChrisCB65** [comment]
Wow! Already fixed and tested. It's working. Thank you very much.

**Comment by ironmonk88** [comment]
Closing 'cause it's been fixed.
