### ISSUE TITLE
Person sheet is broken as of 1.0.48

### ISSUE THREAD

**Issue by gantonaci** [ironmonk88/monks-enhanced-journal#224]
Every Person journal entry that does not have an associated Actor is failing to load.
This is written to the console:
```
monks-enhanced-journal |  TypeError: Cannot read properties of undefined (reading 'id')
    at PersonSheet.js:56:61
    at Actors.find (collection.mjs:46:12)
    at PersonSheet.getData (PersonSheet.js:56:33)
    at async EnhancedJournal.renderSubSheet (enhanced-journal.js:184:32)
```
<html>
<body>

error | @ | monks-enhanced-journal.js:29
-- | -- | --
  | renderSubSheet | @ | enhanced-journal.js:287
  | await in renderSubSheet (async) |   |  
  | _render | @ | enhanced-journal.js:101
  | await in _render (async) |   |  
  | render | @ | foundry.js:3023
  | activateTab | @ | enhanced-journal.js:538
  | await in activateTab (async) |   |  
  | addTab | @ | enhanced-journal.js:478
  | open | @ | enhanced-journal.js:788
  | openJournalEntry | @ | monks-enhanced-journal.js:886
  | clickDocumentName | @ | monks-enhanced-journal.js:204
  | 🎁call_wrapper | @ | libWrapper-wrapper.js:620
  | clickDocumentName | @ | monks-active-tiles.js:4529
  | 🎁call_wrapper | @ | libWrapper-wrapper.js:620
  | 🎁JournalDirectory.prototype._onClickDocumentName#0 | @ | libWrapper-wrapper.js:189
  | dispatch | @ | jquery.min.js:2
  | v.handle | @ | jquery.min.js:2

</body>
</html>

**Comment by gantonaci** [comment]
Thanks. Working in 1.0.49.
