### ISSUE TITLE
Problems saving writings within Monk's Enhanced Journal.

### ISSUE THREAD

**Issue by sethmod** [ironmonk88/monks-enhanced-journal#237]
Even finding the save button very small, every time I click and close it doesn't save what I wrote, in fact I lost everything I wrote trusting it would work when I saved, closed the document, it didn't save and lost everything (fault mine, I admit, I should have put the document elsewhere first). I'm trying to solve this problem, I just updated thinking it would fix it and it didn't, and the module looks amazing, especially for my PF2 desk (Pathfinder 2). Could it be some incompatibility or is it a module problem?

Modules: I use Custom Journal too, the union of modules would be wonderful.

NOTE: I use Foundry VTT's V9 and I also use the Pathfinder 2e system.

**Comment by sethmod** [comment]
In my console appears this error: 

Uncaught (in promise) TypeError: form.elements is not iterable
[Detected 1 package: monks-enhanced-journal]
    at FormDataExtended.process (foundry.js:46330:26)
    at new FormDataExtended (foundry.js:46318:10)
    at ImageJournal._getSubmitData (foundry.js:3880:16)
    at ImageJournal._onSubmit (foundry.js:3845:27)
    at ImageJournal.saveEditor (foundry.js:3999:31)
    at ImageJournal.subsheet.saveEditor (enhanced-journal.js:257:44)
    at _x.save_onsavecallback (foundry.js:4036:40)
    at _x.execCallback (tinymce.min.js:9:366461)
    at plugin.min.js:9:325
    at _x.<anonymous> (plugin.min.js:9:563)
    at commands.exec.<computed> (tinymce.min.js:9:348648)
    at K1.execCommand (tinymce.min.js:9:347409)
    at _x.execCommand (tinymce.min.js:9:367741)
    at Object.onAction (plugin.min.js:9:1199)
    at theme.min.js:9:311150
    at theme.min.js:9:129935
    at theme.min.js:9:311112
    at theme.min.js:9:32672
    at St (theme.min.js:9:5766)
    at run (theme.min.js:9:32649)
    at e (theme.min.js:9:38628)
    at theme.min.js:9:1078
    at theme.min.js:9:151798
    at Object.fold (theme.min.js:9:5248)
    at Zb (theme.min.js:9:151690)
    at cy (theme.min.js:9:159553)
    at sy (theme.min.js:9:159660)
    at theme.min.js:9:153704
    at Lu (theme.min.js:9:41520)
    at Object.triggerEvent (theme.min.js:9:153678)
    at nu (theme.min.js:9:37503)
    at vr (theme.min.js:9:28656)
    at yr (theme.min.js:9:28731)
    at t (theme.min.js:9:89492)
    at e (theme.min.js:9:38628)
    at theme.min.js:9:1078
    at theme.min.js:9:151798
    at Object.fold (theme.min.js:9:5248)
    at Zb (theme.min.js:9:151690)
    at cy (theme.min.js:9:159553)
    at sy (theme.min.js:9:159660)
    at theme.min.js:9:153599
    at Lu (theme.min.js:9:41520)
    at Object.triggerEvent (theme.min.js:9:153566)
    at theme.min.js:9:150614
    at HTMLDivElement.En.a (theme.min.js:9:11368)

**Comment by ironmonk88** [comment]
Is this still an issue?
