### ISSUE TITLE
[BUG] Brief description of your issue

### ISSUE THREAD

**Issue by masasume** [ironmonk88/monks-enhanced-journal#464]
**Describe the bug**
I use lavaflow to import my entries that are ordered by folders from obsidian into foundry.

Showing players specific journal entries that are importet with lavaflow generate the following message for the players: "user lack permission to update JournalEntryPage [Journal_ID] in parent JournalEntry [Journal_ID]." Important: The journal entries are correctly shown, but are shown the error as well. This error doesn't happen, if i deactivate monks enhanced journal.

How to reproduce: 

**To Reproduce**
1. Download the following files: https://1drv.ms/u/s!AlPiYwrWva9Ak5tZb0RbuxPUKzR-4g?e=5Dg6pX
2. Download and activate lavaflow
3. Import the downloaded files

**Expected behavior**
The specified error isn't shown.

**Screenshots**
![Screenshot 2023-01-01 171135](https://user-images.githubusercontent.com/72503373/210177495-f7458855-8ae9-4fe1-a4d0-f377bed99618.png)

![Screenshot 2023-01-01 171144](https://user-images.githubusercontent.com/72503373/210177492-2d279306-9bb1-4bdc-8c1c-513d43781e77.png)

![Screenshot 2023-01-01 171149](https://user-images.githubusercontent.com/72503373/210177481-6bc13cb4-f7f2-45a3-8e1f-badd1a902756.png)

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version V10
 - System D&D5e
 - Module version 10.9
 - Are there any errors in the console:
Uncaught (in promise) Error: User Katha lacks permission to update JournalEntryPage [oglA9LoiVVqyNBj2] in parent JournalEntry [2Jg6dQmWdF9qgbuL]
[No packages detected] at ServerDatabaseBackend._updateEmbeddedDocuments (/home/ubuntu/foundry/resources/app/dist/database/backend/server-backend.mjs:1:4556) at async Semaphore._try (/home/ubuntu/foundry/resources/app/common/utils/semaphore.mjs:101:17)

**Comment by bularzik** [comment]
This looks like it no longer applies — Lavaflow is no longer distributed, so the reported import path can't occur on new installs. I think this can be closed, but happy to reopen if it's still relevant on a current version.
