### ISSUE TITLE
bug: JournalTextPageSheet.prototype.onAutosave issue IDed by LibWrapper

### ISSUE THREAD

**Issue by TimPasquini** [ironmonk88/monks-enhanced-journal#487]
LibWrapper returned the following information. Foundry is on 10.290; Monks is on 10.12

```
Uncaught (in promise) LibWrapperPackageError: Error detected in module Monk's Enhanced Journal.

This is *not* a libWrapper bug.

Find information about this module here: https://github.com/ironmonk88/monks-enhanced-journal
Report this issue here: https://github.com/ironmonk88/monks-enhanced-journal/issues

== Technical Details:
Detected by libWrapper.
Package ID= monks-enhanced-journal
Error= Can't wrap 'JournalTextPageSheet.prototype.onAutosave', target does not exist or could not be found.

[Detected 1 package: monks-enhanced-journal]
    at new 🎁constructor (libWrapper-wrapper.js:111:11)
    at libWrapper-api.js:82:18
    at se (libWrapper-api.js:155:9)
    at 🎁register [as register] (libWrapper-api.js:525:14)
    at MonksEnhancedJournal.init (monks-enhanced-journal.js:805:24)
    at Object.fn (monks-enhanced-journal.js:3483:26)
    at #call (foundry.js:724:20)
    at Hooks.callAll (foundry.js:681:17)
    at Game.initialize (foundry.js:7767:11)
    at 🎁call_wrapped [as call_wrapped] (libWrapper-wrapper.js:507:22)
    at 🎁libWrapperInit (libWrapper-api.js:805:11)
```

**Comment by ironmonk88** [comment]
Should be fixed in the latest version.
