### ISSUE TITLE
[BUG] DCs cause Console Error and are not addable in investigator/gumshoe system

### ISSUE THREAD

**Issue by Muwak77** [ironmonk88/monks-enhanced-journal#605]
**Describe the bug**
Wenn i try to add a DC in a new Tab noting happens but an error-message appears in the Browser Console:

foundry.js:753 TypeError: An error occurred while rendering DCConfig 86. Cannot read properties of undefined (reading 'skillList')
[Detected 1 package: monks-enhanced-journal]
    at DCConfig.getData (dc-config.js:27:44)
    at DCConfig._render (foundry.js:5785:29)
    at DCConfig._render (foundry.js:6503:17)
    at DCConfig.render (foundry.js:5742:10)
    at EncounterSheet.createDC (EncounterSheet.js:306:32)
    at HTMLAnchorElement.i (jquery.min.js:2:89049)
    at HTMLAnchorElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)

**To Reproduce**
- Open An Encouter
- Switch to the DCs Tab
- Click "ADD"

**Expected behavior**
I Am Using the Gumshoe System which is DC-Based so there should be a "Select Ability" dialog to add a DC

**Please complete as much of the following information as possible:**
 - Browser Chrome
 - Foundry Version 11
 - System investigator/gumshoe 
 - Module version 11.03

**Comment by ironmonk88** [comment]
Fixed issue where systems without accessible skill lists were being shown the DC Config.
