### ISSUE TITLE
[BUG] Monk's Enhanced Journal not working when Monk's Active tile triggers is enabled

### ISSUE THREAD

**Issue by BuckaruBanzai** [ironmonk88/monks-enhanced-journal#722]
I installed a map pack, which required Monk's Active tile triggers.  When this module is enabled, Monk's Enhanced Journal stops working.  

I also get this error when Monk's Active tile triggers is enabled.

2024-09-23 04:21:35 [error] JournalEntryPage [0v3soibyd8h6FRgJ] validation errors:
  type: person is not a valid choice
Error: JournalEntryPage [0v3soibyd8h6FRgJ] validation errors:
type: person is not a valid choice
at DataModelValidationFailure.asError (file:///opt/foundryvtt/common/data/validation-failure.mjs:81:12)
at JournalEntryPage.validate (file:///opt/foundryvtt/common/abstract/data.mjs:308:59)
at JournalEntryPage.updateSource (file:///opt/foundryvtt/common/abstract/data.mjs:397:10)
at ServerDatabaseBackend._updateDocuments (file:///opt/foundryvtt/dist/database/backend/server-backend.mjs:1:4328)
at async Semaphore._try (file:///opt/foundryvtt/common/utils/semaphore.mjs:101:17)

**Comment by Crowguard** [comment]
@BuckaruBanzai This is a combination of an issue with Libwrapper and Forge. Update Libwrapper to 1.13.1.0.

**Comment by bularzik** [comment]
This looks like it no longer applies — the thread's own follow-up resolves this as a libWrapper/Forge caching bug, which has since been fixed upstream. I think this can be closed, but happy to reopen if it's still relevant on a current version.
